export const DOM = Object.freeze({
  uploadBtn: document.getElementById('uploadBtn'),
  fetchAllBtn: document.getElementById('fetchAllBtn'),
  fetchBlockedBtn: document.getElementById('fetchBlockedBtn'),
  pauseBtn: document.getElementById('pauseBtn'),
  stopBtn: document.getElementById('stopBtn'),
  progressBar: document.getElementById('progressBar'),
  progressText: document.getElementById('progressText'),
  rawTotalStat: document.getElementById('rawTotalStat'),
  filteredStat: document.getElementById('filteredStat'),
  rawFollowersStat: document.getElementById('rawFollowersStat'),
  validFollowersStat: document.getElementById('validFollowersStat'),
  friendsCountStat: document.getElementById('friendsCountStat'),
  blockedCountStat: document.getElementById('blockedCountStat'),
  tableBody: document.getElementById('tableBody'),
  downloadProfilesBtn: document.getElementById('downloadProfilesBtn'),
  downloadFollowingBtn: document.getElementById('downloadFollowingBtn'),
  downloadSQLiteBtn: document.getElementById('downloadSQLiteBtn'),
  dbStatusEl: document.getElementById('dbStatus'),
  profileTableHead: document.querySelector('#profileTable thead'),
  switchBlockBtn: document.getElementById('switchBlock'),
  getFailedBtn: document.getElementById('getFailed'),
  compareUserBtn: document.getElementById('compareUser'),
  compareBlockedBtn: document.getElementById('compareBlocked'),
  failedPre: document.getElementById('failed'),
  comparePre: document.getElementById('compare'),
  blockedPre: document.getElementById('blocked'),
  fetchBlock: document.getElementById('fetchBlock'),
  failedBlock: document.getElementById('failedBlock'),
  settingsBtn: document.getElementById('settingsBtn'),
  settingsModal: document.getElementById('settingsModal'),
  closeSettingsBtn: document.getElementById('closeSettingsBtn'),
  modalOverlay: document.getElementById('modalOverlay'),
  saveSettingsBtn: document.getElementById('saveSettingsBtn'),
  apiKeyInput: document.getElementById('apiKeyInput'),
  concurrencyInput: document.getElementById('concurrencyInput'), // single
  timeoutInput: document.getElementById('timeoutInput'),
  fetchAvatarBlobsCheckbox: document.getElementById('fetchAvatarBlobsCheckbox'),
  columnToggleBtn: document.getElementById('columnToggleBtn'),
  columnDropdown: document.getElementById('columnDropdown'),
  dbFilePathInput: document.getElementById('dbFilePathInput'),
  loadingOverlay: document.getElementById('loadingOverlay'),
  rawTotalPosts: document.getElementById('rawTotalPosts'),
  processedPosts: document.getElementById('processedPosts'),
  populatePostsCheckbox: document.getElementById('populatePostsCheckbox'),
});